spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.157.91:3306/sx_cms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    cache: true  #缓存
  devtools:
    restart:
      enabled: true #开启
      additional-paths: src/main/java #监听目录

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.moon.dao

logging:
  config: classpath:log/logback.xml
  path: E:/huishen/log/cx-cms
  level:
    com:
      moon:
        dao: debug

